language: node_js

node_js:
  - "node"

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - yarn test

install: 
  - yarn && yarn compile

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn